# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Highlights' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Highlights

  pod 'R.swift'
  pod 'SwiftyStoreKit'
  pod 'NVActivityIndicatorView/Extended'
  pod 'TensorFlowLiteSwift'
  pod 'TensorFlowLiteTaskText', '~> 0.0.1-nightly'
  pod 'Firebase/Analytics'


  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/MLModelInterpreter'	

end
